name: sample

on: push

jobs:
  git:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      name: git branch checkout
      with:
        ref: master


    - name: show git branch
      run: git branch  
      